enum ResponseStatus {
  success,
  noContent,
  timeout,
  incompleteRequest,
  invalidRequest,
  networkFailure,
  unknownError,
  invalidCode,
  verified,
  notVerified,
  unauthorized,
  noMessages,
  userNotVerified,
  userNotExist,
}